services:
  backend:
    image: sushilbajpai/expense-tracker-backend
    container_name: expense-tracker-backend
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - PORT=5000
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=7d
    networks:
      - expense-tracker-network

  frontend:
    image: sushilbajpai/expense-tracker-frontend
    container_name: expense-tracker-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    networks:
      - expense-tracker-network

  mongodb:
    image: mongo:latest
    container_name: expense-tracker-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - expense-tracker-network

networks:
  expense-tracker-network:
    driver: bridge

volumes:
  mongodb_data:
